flags: {}
extra-package-dbs: []
packages:
- .
- ../uniform/uniform-algebras
- ../uniform/uniform-strings
- ../uniform/uniform-error
# - ../fromOthers/haskell-partial-order_af
extra-deps:
- test-invariant-0.4.5.0
resolver: nightly-2018-04-03
