flags: {}
extra-package-dbs: []
packages:
- .
#- ../uniform/uniform-strings
#- ../uniform/uniform-error
#- ../uniform/uniform-convenience
#- ../uniform/uniform-fileio
- ../uniform/uniform-algebras

extra-deps:
resolver: nightly-2018-04-03
